### ISSUE TITLE
Set your weather service failing

### ISSUE THREAD

**Issue by ired** [jason0x43/jc-weather#6]
Thank you for your workflow. Unfortunately I can't get it to work.
After setting an API key for forecast.io and checking weather the workflow tells me that the weather service was not set (i have tried multiple times).

When I turn on the debugging tool from Alfred it shows me a snippet of applescript which apparently don't get the API Key.

![screen shot 2015-01-28 at 15 20 58](https://cloud.githubusercontent.com/assets/1674589/5939230/5cef8738-a702-11e4-8c30-2f2e56bc1b7f.png)

**Comment by jason0x43** [comment]
This is fixed in the [latest release](https://github.com/jason0x43/jc-weather/releases/tag/v20150128.0). Give it a try and reopen this issue if you're still having problems.

Note that Alfred's debug window prefixes any message that prints to the stderr stream with "[ERROR:". Many packages use stderr for normal logging, so it often doesn't indicate an error.

**Comment by ired** [comment]
it has worked! thank you.
